/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.yazalistirmalari;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import javax.swing.JFileChooser;

/**
 *
 * @author acer
 */
public class Not_Defteri extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Not_Defteri.class.getName());

    /**
     * Creates new form Not_Defteri
     */
    public Not_Defteri() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jFileChooser1.addActionListener(this::jFileChooser1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
   // filechooser için onay butonuna basıldığında aktif olan eventtir.
        String butonAdi = evt.getActionCommand();

        // Eğer kullanıcı onay butonuna ("Aç" veya "Kaydet") bastıysa:
        if (butonAdi.equals(JFileChooser.APPROVE_SELECTION)) {
            
            File secilenDosya = jFileChooser1.getSelectedFile();

            // Kullanıcıya ne yapmak istediğini soruyoruz:
            // EVET -> Dosyayı oku ve konsola yazdır
            // HAYIR -> Dosyaya yeni veri yazdır
            int secim = javax.swing.JOptionPane.showConfirmDialog(
                    this, 
                    "Dosyayı okumak (Açmak) istiyorsanız EVET, \nYeni not yazıp kaydetmek istiyorsanız HAYIR butonuna bakın.", 
                    "Ne yapmak istersiniz?", 
                    javax.swing.JOptionPane.YES_NO_OPTION
            );

            // ==========================================
            // 1. SENARYO: KULLANICI EVET (OKUMA) SEÇTİYSE
            // ==========================================
            if (secim == javax.swing.JOptionPane.YES_OPTION) {
                
                try (BufferedReader reader = new BufferedReader(new FileReader(secilenDosya))) {
                    
                    String dosyaIcerigi = "";
                    String satir;

                    while ((satir = reader.readLine()) != null) {
                        dosyaIcerigi = dosyaIcerigi + satir + "\n"; 
                    }

                    System.out.println("--- DOSYA İÇERİĞİ ---");
                    System.out.println(dosyaIcerigi);
                    System.out.println("---------------------");

                } catch (Exception e) {
                    System.out.println("Okuma hatası: " + e.getMessage());
                }

            // ==========================================
            // 2. SENARYO: KULLANICI HAYIR (YAZMA) SEÇTİYSE
            // ==========================================
            } else if (secim == javax.swing.JOptionPane.NO_OPTION) {
                
                // İşte o beklediğimiz girdi kutusu artık sorunsuz bir şekilde açılacak!
                String kullaniciNotu = javax.swing.JOptionPane.showInputDialog(this, "Not defterine kaydetmek istediğiniz yazıyı girin:");

                if (kullaniciNotu != null) {
                    
                    try (BufferedWriter writer = new BufferedWriter(new FileWriter(secilenDosya,true))) {
                        
                        writer.write(kullaniciNotu+ System.lineSeparator());
                        
                        System.out.println("=> Kullanıcının yazdığı not başarıyla dosyaya kaydedildi!");
                        System.out.println("Kaydedilen Not: " + kullaniciNotu);

                        // Dosyayı bilgisayarda otomatik olarak fırlatıp açıyoruz:
                        if (java.awt.Desktop.isDesktopSupported()) {
                            java.awt.Desktop masaustu = java.awt.Desktop.getDesktop();
                            if (secilenDosya.exists()) {
                                masaustu.open(secilenDosya); 
                            }
                        }

                    } catch (Exception e) {
                        System.out.println("Yazma veya dosyayı açma hatası: " + e.getMessage());
                    }
                }
    }}
    }//GEN-LAST:event_jFileChooser1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Not_Defteri().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    // End of variables declaration//GEN-END:variables
}
